# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jaume Durany
email: jdurany@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Optimist & continuously looking to improve. Passionate about developing people & teams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jdurany.github.io" # the base hostname & protocol for your site
twitter_username: jaumedurany
github_username:  jdurany

# Build settings
markdown: kramdown
